name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'
      - '!.github\workflows\**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:

    - name: Checkout qmole-source-site
      uses: actions/checkout@v4
    
    - name: Mkdir & Mv
      run: |
        mkdir -p /home/runner/tmp > /dev/null
        cp -v ./index.html /home/runner/tmp/index.html
        cp -v ./Installation.html /home/runner/tmp/Installation.html
        cp -v ./Fix.html /home/runner/tmp/Fix.html
        cp -v ./About.html /home/runner/tmp/About.html
        cp -v ./CNAME /home/runner/tmp/CNAME
        cp -r -v ./js /home/runner/tmp/js
        cp -r -v ./css /home/runner/tmp/css

    - name: HTML/CSS/JS Minifier
      uses: docker://devatherock/minify-js:3.0.0
      with:
        add_suffix: false

    - name: Mkdir & Mv
      run: |
        mkdir -p /home/runner/tmp > /dev/null
        cp -u -v ./index.html /home/runner/tmp/index.html
        cp -u -v ./Installation.html /home/runner/tmp/Installation.html
        cp -u -v ./Fix.html /home/runner/tmp/Fix.html
        cp -u -v ./About.html /home/runner/tmp/About.html
        cp -u -v ./CNAME /home/runner/tmp/CNAME
        cp -u -r -v ./js /home/runner/tmp/js
        # cp -u -r -v ./css /home/runner/tmp/css

    - name: Checkout qmole-packages
      uses: actions/checkout@v4
      with:
        repository: chriskmanx/qmole-packages
        lfs: 'true'
        submodules: 'recursive'

    - name: Build site
      run: |
        cp -v /home/runner/tmp/index.html REPO/index.html
        cp -v /home/runner/tmp/Installation.html REPO/Installation.html
        cp -v /home/runner/tmp/Fix.html REPO/Fix.html
        cp -v /home/runner/tmp/About.html REPO/About.html
        cp -v /home/runner/tmp/CNAME REPO/CNAME
        cp -r -v /home/runner/tmp/js REPO/js
        cp -r -v /home/runner/tmp/css REPO/css
        cp -v qmole.png REPO/qmole.png

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        path-to-root: ./REPO
        base-url-path: https://qmole.pj568.sbs/

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './REPO'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4