name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:

    - name: Checkout qmole-source-site
      uses: actions/checkout@v4

    - name: Mkdir & Mv
      run: |
        mkdir /home/runner/tmp
        cp -v ./index.html /home/runner/tmp/index.html
        cp -v ./CNAME /home/runner/tmp/CNAME

    - name: HTML/CSS/JS Minifier
      uses: docker://devatherock/minify-js:3.0.0
      with:
        directory: '/home/runner/tmp/'
        add_suffix: false

    - name: Checkout qmole-packages
      uses: actions/checkout@v4
      with:
        repository: chriskmanx/qmole-packages

    - name: Build site
      run: |
        cp -v /home/runner/tmp/index.html REPO/index.html
        cp -v /home/runner/tmp/CNAME REPO/CNAME
        cp -v qmole.png REPO/qmole.png

    # - uses: JamesIves/github-pages-deploy-action@v4
    #   with:
    #     folder: ./REPO

    - name: test-Check
      uses: actions/upload-artifact@v4
      with:
        name: test-Files
        path: ./REPO/index.html